import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { fetchRecipes } from "./_lib/fetch";
import { UserProvider } from "./_lib/recipes-provider";
import { Suspense } from "react";
// import "./_lib/setup-fetch-logger";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userPromise = fetchRecipes(); // do NOT await

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <UserProvider userPromise={userPromise}>
          <Suspense fallback={<div>loading...in root layout</div>}>
            {children}
          </Suspense>
        </UserProvider>
      </body>
    </html>
  );
}
